<a href="https://colab.research.google.com/github/vainaijr/aiStartUp/blob/master/snippets_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# networkx

In [0]:
import networkx as nx
from networkx import nx

In [0]:
nx.grid_2d_graph
nx.lollipop_graph
nx.is_graphical

nx.configuration_model

for line in nx.generate_adjlist
for v in G.nodes():
nx.single_source_shortest_path_length

nx.radius
nx.diameter
nx.eccentricity
nx.center
nx.periphery
nx.density

nx.write_edgelist
nx.read_edgelist
nx.draw


# video

In [0]:
from IPython.display import HTML

# Youtube
HTML('<iframe width="560" height="315" src="https://www.youtube.com/embed/S_f2qV2_U00?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>')

# eliot

In [0]:
!pip install eliot
!pip install eliot-tree

In [0]:
from eliot import log_call, to_file

to_file(open("out.log", "w"))

In [0]:
!eliot-tree out.log | grep -A1 double.*started

# function__

In [0]:
def add(a: int, b: int) -> int:
  """adds two numbers"""
  x = a + b
  return x

In [0]:
print(add.__doc__)

adds two numbers


In [0]:
print(add.__annotations__)

{'a': <class 'int'>, 'b': <class 'int'>, 'return': <class 'int'>}


In [0]:
print(add.__code__.co_varnames)

('a', 'b', 'x')


In [0]:
print(add.__closure__)

None


In [0]:
from inspect import signature
signature(add).parameters

mappingproxy({'a': <Parameter "a:int">, 'b': <Parameter "b:int">})

# call dunder

In [0]:
class Averager():
  def __init__(self):
    self.series = []
  
  def __call__(self, new_value):
    self.series.append(new_value)
    total = sum(self.series)
    return total / len(self.series)    

In [0]:
avg = Averager()

In [0]:
avg.__call__(10)

10.0

In [0]:
object.__call__?

In [0]:
def make_average():
  series = []
  
  def averager(new_value):
    series.append(new_value)
    total = sum(series)
    return total / len(series)
  
  return averager

In [0]:
avg = make_average()

In [0]:
avg(10)

10.0

# decorators in the standard library

In [0]:
@property
@classmethod
@staticmethod
@functools.wraps
@functools.singledispatch
@functools.total_ordering
@functools.lru_cache

# descriptors

In [0]:
# a descriptor encapsulates attribute getting / setting logic in a reusable way

In [0]:
# it is posible to use any class that implements __get__ or __set__ as a descriptor

# method resolution order

In [0]:
import inspect

In [0]:
inspect.getmro(type(3.14))

(float, object)

In [0]:
(1 == 1).__class__.__mro__

(bool, int, object)

# nvcc

In [0]:
!pip install git+git://github.com/andreinechaev/nvcc4jupyter.git

In [0]:
%load_ext nvcc_plugin

In [0]:
%%cu

# os version 

In [0]:
%%bash
echo "$(</etc/os-release)"

# grep

In [0]:
!grep "WORLD" world/hi.txt

In [0]:
!grep -i "WORLD" world/hi.txt

hello world


In [0]:
!grep -iv "WORLD" world/hi.txt

In [0]:
!grep -v "WORLD" world/hi.txt

hello world


In [0]:
!grep -rn "he" *

world/hi.txt:1:hello world


# AdaptiveConcatPool2d

In [0]:
class AdaptiveConcatPool2d(nn.Module):
  def __init__(self, sz=1):
    super().__init__()
    self.output_size = sz
    self.ap = nn.AdaptiveAvgPool2d(sz)
    self.mp = nn.AdaptiveMaxPool2d(sz)
  
  def forward(self, x):
    return torch.cat([self.mp(x), self.ap(x)], 1)

In [0]:
nh = 40

m_new = nn.Sequential(
    m_cut, AdaptiveConcatPool2d(), Flatten(),
    nn.Linear(ni*2, data.c_out))

In [0]:
nh = 40

m_new = nn.Sequential(m_cut, AdaptiveConcatPool2d(), Flatten(), nn.Linear(ni * 2, data.c_out))

# in-place

In [0]:
# example of not in-place

In [0]:
a = torch.randn(1)
b = torch.randn(1)

In [0]:
id(a)

140060066035968

In [0]:
id(b)

140060066034240

In [0]:
a = a + b # not in-place

In [0]:
id(a) # changed because not in-place

140060066034672

In [0]:
# example of in-place

In [0]:
c = torch.randn(1)
d = torch.randn(1)

In [0]:
id(c)

140060066037336

In [0]:
id(d)

140060066034888

In [0]:
c += d # +=, *= in-place

In [0]:
id(c) # no change because in-place

140060066037336

In [0]:
# another example of in-place

In [0]:
e = torch.randn(1)
f = torch.randn(1)

In [0]:
id(e)

140060066050624

In [0]:
id(f)

140060066050768

In [0]:
e.add_(f)

tensor([-1.9524])

In [0]:
id(e) # no change because in-place

140060066050624

In [0]:
# in PyTorch _ as postfix means in-place

In [0]:
e.add_(f) # in-place
e.sub_(f) # in-place

tensor([-1.9524])

In [0]:
id(e)

140060066050624

# fastai_listify

In [0]:
!pip install fastai
from fastai.train import listify
import torch

In [0]:
x = [1, 2, 3]
y = torch.arange(12)

In [0]:
x

[1, 2, 3]

In [0]:
y

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
z = listify((1), x)
z

[1, 1, 1]

In [0]:
a = listify(1, y)
a

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [0]:
b = listify((1, 2, 3), x)
b

[1, 2, 3]

In [0]:
c = listify('g', x)
c

['g', 'g', 'g']

# expand_as

In [0]:
a = torch.tensor([1, 2, 3])

In [0]:
b = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [0]:
c = a.expand_as(b)

In [0]:
c

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [0]:
d = a + b

In [0]:
d

tensor([[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12]])

# bs_val

In [0]:
bs*2

# fastai_callbacks

In [0]:
def train(learn, epochs, callback, metrics):
  cb_handler = CallbackHandler(callbacks)
  cb_handler.on_train_begin(epochs, learn, metrics)
  for epoch in range(epochs):
    learn.model.train()
    cb_handler.on_epoch_begin(epoch)
    for xb, yb in learn.data.train_dl:
      xb, yb = cb_handler.on_batch_begin(xb, yb)
      out = learn.model(xb)
      out = cb_handler.on_loss_begin(out)
      loss = learn.loss_func(out, yb)
      loss, skip_backward = callbacks.on_loss_begin(loss)
      if not skip_backward:
        loss.backward()
      if not cb_handler.on_step_begin():
        learn.opt.step()
      if not cb_handler.on_step_end():
        learn.opt.zero_grad()
      if not callbacks.on_batch_end():
        break
    val_loss, mets = validate(learn.data.valid_dl, model, metrics)
    if not callbacks.on_epoch_end(val_loss, mets):
      break
  callbacks.on_train_end()

In [0]:
class LRScheduler(LearnerCallback):
  def on_batch_begin(self, iteration, **kwargs):
    self.learn.opt.lr = my_function(iteration)

In [0]:
class EarlyStopping(Callback):
  def on_epoch_end(self, last_metrics, **kwargs):
    if not_happy(last_metrics):
      return {'stop_training': True}

In [0]:
class ParallelTrainer(LearnerCallback):
  _order = 20
  def on_train_begin(self, **kwargs):
    self.learn.model = DataParallel(self.learn.model)
  def on_train_end(self, **kwargs):
    self.learn.model = self.learn.model.module

In [0]:
class GradientClipping(LearnerCallback):
  def __init__(self, learn:Learner, clip:float = 0.):
    super().__init__(learn)
    self.clip = clip
  
  def on_backward_end(self, **kwargs):
    if self.clip:
      nn.utils.clip_grad_norm_(self.learn.model.parameters(), self.clip)

# class

In [0]:
class Foo():
  xyz = 0
  
  def __init__(self, x):
    self.y = x
  
  def __repr__(self):
    return str(self.y)
  
  def __getattribute__(self, item):
    if item.startswith('cur'):
      raise AttributeError
    return object.__getattribute__(self,item)
  
  def __getattr__(self, item):
    self.__dict__[item]=0
    return 0
  
  @staticmethod
  def x():
    print("static method")
  
  @classmethod
  def ye(cls, name):
    print("class method", cls, name)
    cls.xyz = name
    return cls(100)
  
  def __getitem__(self, key):
    return self.y[key]
  
  def __add__(self, a):
    return A(self.y + a.y)
    
  def __call__(self):
    return 5

# closure

In [0]:
def do(x):
  print('x:', x)
  def _add(a):
    print('a:', a)
    return x + a # 2 + 1
  
  return _add

In [0]:
x = do(2)

x: 2


In [0]:
x

<function __main__.do.<locals>._add>

In [0]:
x(1)

a: 1


3

# callback class

In [0]:
def do(cb1, i, *args, **kwargs):
  return cb1(i), cb1.add_one(i)

In [0]:
class T():
  def __init__(self):
    self.x = 5
  
  def add_one(self, e):
    return e + 1
  
  def __call__(self, d):
    return d

In [0]:
x = T()

In [0]:
hasattr(x, 'add_one')

True

In [0]:
do(x, 1)

(1, 2)

# GeneralRelu

In [0]:
class GeneralRelu(nn.Module):
    def __init__(self, leak=None, sub=None, maxv=None):
        super().__init__()
        self.leak,self.sub,self.maxv = leak,sub,maxv

    def forward(self, x): 
        x = F.leaky_relu(x,self.leak) if self.leak is not None else F.relu(x)
        if self.sub is not None: x.sub_(self.sub)
        if self.maxv is not None: x.clamp_max_(self.maxv)
        return x

# LayerNorm

In [0]:
class LayerNorm(nn.Module):
    __constants__ = ['eps']
    def __init__(self, eps=1e-5):
        super().__init__()
        self.eps = eps
        self.mult = nn.Parameter(tensor(1.))
        self.add  = nn.Parameter(tensor(0.))

    def forward(self, x):
        m = x.mean((1,2,3), keepdim=True)
        v = x.std ((1,2,3), keepdim=True)
        x = (x-m) / ((v+self.eps).sqrt())
        return x*self.mult + self.add

# InstanceNorm

In [0]:
class InstanceNorm(nn.Module):
    __constants__ = ['eps']
    def __init__(self, nf, eps=1e-0):
        super().__init__()
        self.eps = eps
        self.mults = nn.Parameter(torch.ones (nf,1,1))
        self.adds  = nn.Parameter(torch.zeros(nf,1,1))

    def forward(self, x):
        m = x.mean((2,3), keepdim=True)
        v = x.std ((2,3), keepdim=True)
        res = (x-m) / ((v+self.eps).sqrt())
        return res*self.mults + self.adds

# RunningBatchNorm

In [0]:
class RunningBatchNorm(nn.Module):
    def __init__(self, nf, mom=0.1, eps=1e-5):
        super().__init__()
        self.mom,self.eps = mom,eps
        self.mults = nn.Parameter(torch.ones (nf,1,1))
        self.adds = nn.Parameter(torch.zeros(nf,1,1))
        self.register_buffer('sums', torch.zeros(1,nf,1,1))
        self.register_buffer('sqrs', torch.zeros(1,nf,1,1))
        self.register_buffer('batch', tensor(0.))
        self.register_buffer('count', tensor(0.))
        self.register_buffer('step', tensor(0.))
        self.register_buffer('dbias', tensor(0.))

    def update_stats(self, x):
        bs,nc,*_ = x.shape
        self.sums.detach_()
        self.sqrs.detach_()
        dims = (0,2,3)
        s = x.sum(dims, keepdim=True)
        ss = (x*x).sum(dims, keepdim=True)
        c = self.count.new_tensor(x.numel()/nc)
        mom1 = 1 - (1-self.mom)/math.sqrt(bs-1)
        self.mom1 = self.dbias.new_tensor(mom1)
        self.sums.lerp_(s, self.mom1)
        self.sqrs.lerp_(ss, self.mom1)
        self.count.lerp_(c, self.mom1)
        self.dbias = self.dbias*(1-self.mom1) + self.mom1
        self.batch += bs
        self.step += 1

    def forward(self, x):
        if self.training: self.update_stats(x)
        sums = self.sums
        sqrs = self.sqrs
        c = self.count
        if self.step<100:
            sums = sums / self.dbias
            sqrs = sqrs / self.dbias
            c    = c    / self.dbias
        means = sums/c
        vars = (sqrs/c).sub_(means*means)
        if bool(self.batch < 20): vars.clamp_min_(0.01)
        x = (x-means).div_((vars.add_(self.eps)).sqrt())
        return x.mul_(self.mults).add_(self.adds)

# hooks

In [0]:
#export
class ListContainer():
    def __init__(self, items): self.items = listify(items)
    def __getitem__(self, idx):
        if isinstance(idx, (int,slice)): return self.items[idx]
        if isinstance(idx[0],bool):
            assert len(idx)==len(self) # bool mask
            return [o for m,o in zip(idx,self.items) if m]
        return [self.items[i] for i in idx]
    def __len__(self): return len(self.items)
    def __iter__(self): return iter(self.items)
    def __setitem__(self, i, o): self.items[i] = o
    def __delitem__(self, i): del(self.items[i])
    def __repr__(self):
        res = f'{self.__class__.__name__} ({len(self)} items)\n{self.items[:10]}'
        if len(self)>10: res = res[:-1]+ '...]'
        return res

In [0]:
#export
from torch.nn import init

class Hooks(ListContainer):
    def __init__(self, ms, f): super().__init__([Hook(m, f) for m in ms])
    def __enter__(self, *args): return self
    def __exit__ (self, *args): self.remove()
    def __del__(self): self.remove()

    def __delitem__(self, i):
        self[i].remove()
        super().__delitem__(i)
        
    def remove(self):
        for h in self: h.remove()

# @xyz.setter

In [0]:
class A():
  def __init__(self, val):
    self.xyz = val # setter call
    # self._xyz = val # no setter call

  @property
  def xyz(self):
    return self._xyz
  
  @xyz.setter
  def xyz(self, t):
    self._xyz = t

# lsuv

In [0]:
#export
def lsuv_module(m, xb):
    h = Hook(m, append_stat)

    while mdl(xb) is not None and abs(h.mean)  > 1e-3: m.bias -= h.mean
    while mdl(xb) is not None and abs(h.std-1) > 1e-3: m.weight.data /= h.std

    h.remove()
    return h.mean,h.std

In [0]:
for m in mods: print(lsuv_module(m, xb))

# setify

In [0]:
from fastai.train import listify
def setify(x):
  return x if isinstance(x, set) else set(listify(x))

# scandir

In [0]:
for x in os.scandir('.'):
  print(x.name)
  if x.is_file():
    print(x)

# hasattr | setattr | getattr

In [0]:
class A():
  def __init__(self, x):
    self.y = x

In [0]:
t = A(1)

In [0]:
t.y

1

In [0]:
hasattr(t, 'y')

True

In [0]:
getattr(t, 'y')

1

In [0]:
setattr(t, 'y', 2)

In [0]:
getattr(t, 'y')

2

In [0]:
t.y

2

In [0]:
setattr(t, 's', 1)

In [0]:
dir(t)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 's',
 'y']

In [0]:
t.s

1

In [0]:
t.y

2

In [0]:
getattr(t, 'z', 0)

0

# compose

In [0]:
from funcy import compose, partial

In [0]:
def add(x, y):
  print("add", x, y)
  return x + y

In [0]:
def subtract(x, y):
  print("subtract", x, y)
  return x - y

In [0]:
def multiply(x, y, z):
  print("multiply", x, y, z)
  return x * y * z

In [0]:
a = partial(add, 5)
b = partial(subtract, 1)
c = partial(multiply, 2, 3)

In [0]:
t = compose(a, b, c)

In [0]:
t(1)

multiply 2 3 1
subtract 1 6
add 5 -5


0

# model_summary

In [0]:
#export
def model_summary(run, learn, data, find_all=False):
    xb,yb = get_batch(data.valid_dl, run)
    device = next(learn.model.parameters()).device#Model may not be on the GPU yet
    xb,yb = xb.to(device),yb.to(device)
    mods = find_modules(learn.model, is_lin_layer) if find_all else learn.model.children()
    f = lambda hook,mod,inp,out: print(f"{mod}\n{out.shape}\n")
    with Hooks(mods, f) as hooks: learn.model(xb)

# optimizer

In [0]:
class Optimizer():
    def __init__(self, params, steppers, **defaults):
        # might be a generator
        self.param_groups = list(params)
        # ensure params is a list of lists
        if not isinstance(self.param_groups[0], list): self.param_groups = [self.param_groups]
        self.hypers = [{**defaults} for p in self.param_groups]
        self.steppers = listify(steppers)

    def grad_params(self):
        return [(p,hyper) for pg,hyper in zip(self.param_groups,self.hypers)
            for p in pg if p.grad is not None]

    def zero_grad(self):
        for p,hyper in self.grad_params():
            p.grad.detach_()
            p.grad.zero_()

    def step(self):
        for p,hyper in self.grad_params(): compose(p, self.steppers, **hyper)

# op

In [0]:
def add(x, y):
  return x + y

In [0]:
def subtract(x, y):
  return x - y

In [0]:
def multiply(x, y):
  return x * y

# set_grad

In [0]:
def set_grad(m, b):
    if isinstance(m, (nn.Linear,nn.BatchNorm2d)): return
    if hasattr(m, 'weight'):
        for p in m.parameters(): p.requires_grad_(b)

# test_near_zero

In [0]:
def test_near_zero(a,tol=1e-3): assert a.abs()<tol, f"Near zero: {a}"

# stats

In [0]:
def stats(x): return x.mean(),x.std()

# Lambda

In [0]:
class Lambda(nn.Module):
  def __init__(self, func):
    super().__init__()
    self.func = func
  
  def forward(self, x):
    return self.func(x)

In [0]:
def flatten(x):
  return x.view(x.shape[0], -1)

In [0]:
e = Lambda(flatten)

# save_features

In [0]:
# we want to see the output after our input is passed to Conv2d layer
# and then we will be able to pass it to any layer

# for saving features after every layer by registering forward hook
class SaveFeatures():
  features=None
  
  def __init__(self, m):
    self.hook = m.register_forward_hook(self.hook_fn)
  
  def hook_fn(self, module, input, output):
    self.features = output
  
  def close(self):
    self.hook.remove()

In [0]:
saved_features_conv = SaveFeatures(children(model)[0])
saved_features_relu = SaveFeatures(children(model)[1])

# General ReLU

In [0]:
class GeneralRelu(nn.Module):
    def __init__(self, leak=None, sub=None, maxv=None):
        super().__init__()
        self.leak,self.sub,self.maxv = leak,sub,maxv

    def forward(self, x): 
        x = F.leaky_relu(x,self.leak) if self.leak is not None else F.relu(x)
        if self.sub is not None: x.sub_(self.sub)
        if self.maxv is not None: x.clamp_max_(self.maxv)
        return x